name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        deno:
          - v1.x
          - canary
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Check formatting, linting, types and run tests
        run: deno task check

      - name: Publish (dry-run)
        run: deno publish --dry-run --allow-dirty

      - name: Create lcov file
        run: deno task cov:gen

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          name: ${{ matrix.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cov.lcov
